iekf_slam_node:
  ros__parameters:
    # -----------------------------
    # IO / Topics / Buffers
    # -----------------------------
    imu_topic: "/imu0"
    lidar_topic: "/livox/lidar"
    imu_buffer_size: 20000

    # -----------------------------
    # LiDAR Preprocess
    # -----------------------------
    reflectivity_filter.enable: true
    reflectivity_filter.min: 5
    reflectivity_filter.max: 255
    distance_filter.enable: true
    distance_filter.min_m: 2.0
    distance_filter.max_m: 200.0
    deskew.enable: true
    downsample.enable: true
    downsample.leaf_size: 0.4
    downsample.update_leaf_size: 0.8
    downsample.map_leaf_size: 0.4

    # -----------------------------
    # IMU Initialization
    # -----------------------------
    imu_init.window_size: 600
    imu_init.gyro_var_threshold: 1.0e-4
    imu_init.accel_var_threshold: 5.0e-2
    imu_init.gravity_norm: 9.81

    # -----------------------------
    # IEKF Predictor (process noise)
    # -----------------------------
    predictor_noise.sigma_acc: 0.10
    predictor_noise.sigma_gyro: 0.01
    predictor_noise.sigma_bg_rw: 1.0e-4
    predictor_noise.sigma_ba_rw: 1.0e-3
    predictor_noise.sigma_g_rw: 0.0

    # -----------------------------
    # IEKF Updater (scan-to-map)
    # -----------------------------
    updater.enable: true
    updater.max_iterations: 2 #每次扫描迭代优化的最大次数
    updater.max_correspondence_distance: 0.5 #构造的平面中的点到平面残差的最大距离，过大可能引入错误匹配，过小可能匹配不足，能衡量平面好坏
    updater.plane_k_neighbors: 8 #每个特征点寻找平面特征时的邻域点数量，过大可能引入非平面点，过小可能平面拟合不稳定
    updater.plane_max_eigen_ratio: 0.2 #允许的最大平面特征点邻域内的最大特征值与次大特征值的比值，过大可能不是平面，过小可能是边界
    updater.sigma_point_to_plane: 0.2 #点到平面残差的标准差，用于更新过程的噪声矩阵R，过大可能匹配不足，过小可能引入错误匹配，现在采用的是固定值
    updater.max_abs_point_to_plane_residual: 0.7 #点到平面残差的绝对值最大值，过大可能引入错误匹配，过小可能匹配不足
    updater.max_update_points: 2500 #每次迭代优化中使用的最大点数，控制优化的计算量，过大可能导致优化过慢，过小可能优化效果不好

    # -----------------------------
    # Local Map
    # -----------------------------
    local_map.voxel_size: 0.5
    local_map.block_size: 15.0
    local_map.history.max_blocks: 200
    local_map.history.enable: true
    local_map.history.radius_xy: 400.0
    local_map.history.half_height: 100.0
    local_map.active.enable: true
    local_map.active.radius_xy: 220.0
    local_map.active.half_height: 80.0
    local_map.active.angle.enable: true
    local_map.active.angle.half_fov_deg: 40.0

    # -----------------------------
    # Publish / Visualization
    # -----------------------------
    publish.odom_topic: "/iekf/odom"
    publish.path_topic: "/iekf/path"
    publish.points_world_topic: "/iekf/points_world"
    publish.map_frame_id: "map"
    publish.base_frame_id: "base_link"
    publish.path.max_length: 2000
    publish.tf.enable: true

    # -----------------------------
    # Runtime / OpenMP
    # -----------------------------
    runtime.omp_num_threads: 16
    runtime.omp_dynamic: false
    runtime.omp_proc_bind: true
    runtime.omp_places: "cores"

    # -----------------------------
    # Extrinsic (LiDAR -> IMU)
    # -----------------------------
    extrinsic.lidar_to_imu.R: [-0.0048858, -0.9997687, -0.0209424, 0.9999720, -0.0047662, -0.0057583, 0.0056571, -0.0209700, 0.9997641]
    extrinsic.lidar_to_imu.P: [0.083, 0.077, 0.035]
